filter:
    excluded_paths: [tests/*, vendor/*]
before_commands:
    - "composer install --prefer-source"
tools:
    php_cs_fixer:
        enabled: true
        config:
            level: all
    php_code_coverage:
        enabled: true
        config_path: phpunit.xml
    php_cpd:
        excluded_dirs: [vendor, tests]
    php_pdepend:
        excluded_dirs: [vendor, tests]
    php_analyzer: true
